### ISSUE TITLE
_py4j.protocol.Py4JError: An error occurred while calling None.org.apache.spark.sql.SparkSession. Trace: py4j.Py4JException: Constructor org.apache.spark.sql.SparkSession([class org.apache.spark.SparkContext, class java.util.HashMap]) does not exist_

### ISSUE THREAD

**Issue by eh3an** [emdgroup/foundry-dev-tools#25]
### Issue checklist

- [X] This is **not** a bug or a feature/enhancement request.
- [X] I searched through the GitHub issues and this issue has not been opened before.

### Issue

Hi all, I tried to run Foundry codes locally on Windows, but I am getting the following error:

_py4j.protocol.Py4JError: An error occurred while calling None.org.apache.spark.sql.SparkSession. Trace:
py4j.Py4JException: Constructor org.apache.spark.sql.SparkSession([class org.apache.spark.SparkContext, class java.util.HashMap]) does not exist_

- Pyspark and Py4j are installed by the package provided in the repository and they look fine.
- I am using transform_pandas decorator.
- Pyspark related environment variables are set.
- same spark and pyspark versions are used(3.4.1)
- Pyspark looks to work(running pyspark --version is returning the version)

 

but wondering what could be the reason.

**Comment by jonas-w** [comment]
Searching for this error, only shows one StackOverflow post, that seems to be related to a version mismatch between spark and pyspark, but you've said that this isn't the case.

What python and java version do you use?
Is this a completely new mamba/conda environment?

Could you try to just run the command `pyspark` (without --version)? This should open a new SparkSession, and an interactive shell. If the creation of the SparkSession also fails, then your installation seems to be faulty and nothing which is related to foundry-dev-tools.

**Comment by eh3an** [comment]
"nothing which is related to foundry-dev-tools": yep, that's why I marked it as not a bug!
pyspark command worked fine in cmd. even running some scripts there also worked. restarting pycharm then windows multiple times did the job. I asked the question here because I thought maybe I did not add some config or environment variables or something on the Foundry side should be checked/fixed...

**Comment by jonas-w** [comment]
Glad you fixed it, does it now work consistently?
