### ISSUE TITLE
[Feature Request]: RID <=> Path Conversion for folders

### ISSUE THREAD

**Issue by dasmy** [emdgroup/foundry-dev-tools#37]
### Issue checklist

- [x] This is a **feature request**/**enhancement**. And not a bug.
- [X] I searched through the GitHub issues and this feature/enhancement has not been requested before.
- [X] I have installed the latest version of Foundry DevTools and don't use an unsupported python version.
- [X] Others could also benefit from this feature or enhancement and it is **not** a very specific use case.

### Feature use case

While functionality for getting all children inside a folder exists (`FoundryRestClient.get_child_objects_of_folder()`), the function requires a folder RID and cannot work with a path. Thus, a conversion function path -> RID for folders would be very handy. Such a function does not exist. However, apparently `FoundryRestClient.get_dataset_rid()` and `FoundryRestClient.get_dataset_path()` also seem to work for folders (at least in a test on my side) despite their name not suggesting this.

### Description of the Feature

It would be desirable to add functions for folders (or even more general for conversion path <=> RID for every object type if possible).

Furthermore, it might make sense to allow functions like `FoundryRestClient.get_child_objects_of_folder()` that only accept an RID to also accept paths. I assume, it should be simple to distinguish inside the function wether a rid or a path was supplied and convert accordingly automatically. This could make the API more lean and simplify usage.

### Alternatives you considered

Instead of using string paths or RIDs in the API, one could also think about a dedicated class for the identifiers similar to the following (which is just a thought, not engineered to the end):
```
class Resource:
  def __init__(self, fc: FoundryRestClient):
      self._fc = fc
      self._rid = None
      self._path = None

  @classmethod
  def from_rid(rid: string, fc: FoundryRestClient):
    r = Resource(fc)
    r._rid = rid
    return r

  @classmethod
  def from_path(path: string, fc: FoundryRestClient):
    r = Resource(fc)
    r._path = path
    return r

  @property
  def rid(self):
    if self._rid is None:
        assert(self._path is not None)
        self._rid = self._fc.path_to_rid(self._path)
    return self._rid

  @property
  def rid(self):
    if self._rid is None:
        assert(self._path is not None)
        self._rid = self._fc.path_to_rid(self._path)
    return self._rid

  @property
  def path(self):
    if self._path is None:
        assert(self._rid is not None)
        self. _path = self._fc.rid_to_path(self._rid)
    return self._path
```

**Comment by jonas-w** [comment]
Hey @dasmy I'm currently working on a v2 of foundry devtools, which is a complete rewrite. I have currently a dataset class which is very similar to what you did. I suppose I'll create a parent class for all resources and maybe further classes that are specific to some resource types.
Thanks

**Comment by dasmy** [comment]
> Hey @dasmy I'm currently working on a v2 of foundry devtools, which is a complete rewrite. I have currently a dataset class which is very similar to what you did. I suppose I'll create a parent class for all resources and maybe further classes that are specific to some resource types.
> Thanks

Sounds good. Let me know if you need support in any way.

**Comment by nicornk** [comment]
@dasmy does the `Resource` class in v2 fullfill your requirement?

**Comment by dasmy** [comment]
Hi @nicornk,
From looking at the code, this feels like perfectly what I meant (even discovered some structure from the original proposal above) just more powerful. So yes and nice work, thanks.

This means, this issue can be closed which I will do in a second.
