### ISSUE TITLE
[Feature Request]: Dataset class should have a nice __repr__

### ISSUE THREAD

**Issue by nicornk** [emdgroup/foundry-dev-tools#62]
### Issue checklist

- [X] This is a **feature request**/**enhancement**. And not a bug.
- [X] I searched through the GitHub issues and this feature/enhancement has not been requested before.
- [X] I have installed the latest version of Foundry DevTools and don't use an unsupported python version.
- [X] Others could also benefit from this feature or enhancement and it is **not** a very specific use case.

### Feature use case

<img width="566" alt="grafik" src="https://github.com/user-attachments/assets/527f38a2-3b3e-4f11-a2d4-17fa2f0bc0da">

Showing the path, rid, information about the current view, branch, maybe statistics... 

### Description of the Feature

see above.

**Comment by jonas-w** [comment]
fixed in v2.0.1
