### ISSUE TITLE
ConnectTimeout error using GitHub Actions

### ISSUE THREAD

**Issue by viola-m-li** [emdgroup/foundry-dev-tools#79]
### Issue checklist

- [X] This is **not** a bug or a feature/enhancement request.
- [X] I searched through the GitHub issues and this issue has not been opened before.

### Issue

Hi,

I have some code where I use Foundry DevTools to interact with the Foundry APIs. Additionally, I've written some tests using pytest. I set `FoundryContext(token_provider=JWTTokenProvider())` by passing `host` and `jwt` as environment variables. This works fine locally, but when I run the tests as a workflow on GitHub, where I provide `host` and `jwt` as GitHub secrets, I get a `ConnectTimeout` error. The values are correctly read from the GitHub secrets. Is there anything else I need to consider when interacting with the Foundry APIs via GitHub Actions? What might be the reason this doesn't work?

Any help would be appreciated. Thanks!

**Comment by nicornk** [comment]
Most probably your Stack can only be reached from within the Company network or from specific IP ranges.
