### ISSUE TITLE
[Bug]: foundry-dev-tools fails to load dataset with page size of more than 1000 files

### ISSUE THREAD

**Issue by mgao-emd** [emdgroup/foundry-dev-tools#87]
### Issue checklist

- [X] This is a **bug** in Foundry DevTools and not a bug in another project. It is also not an enhancement/feature request
- [X] I searched through the GitHub issues and this issue has not been opened before.
- [X] I have installed the latest version of Foundry DevTools and don't use an unsupported python version.

### Description of the bug

foundry-dev-tools loads the dataset uses the catalog-API with a default page size of 1000 dataset files. Is it possible to load dataset of 200K files?

### Steps to reproduce this bug.

Calling return_input().compute() failed with source_df of size >200k files 

def return_input(source_df) -> pl.DataFrame:
    if isinstance(source_df, pl.DataFrame):
        source_df_pl = source_df 
    elif isinstance(source_df, pd.DataFrame):
        # Convert from Pandas to Polars
        source_df_pl = pl.from_pandas(source_df)
    else:
        raise ValueError("Input is neither a Polars nor a Pandas DataFrame.") 
    return source_df_pl

if __name__ == "__main__":
    print(return_input.compute())

### Log output

DatasetNotFoundError: Dataset not found.
------------------------------------REQUEST------------------------------------
METHOD = PUT
CONTENT-TYPE = application/json
ENDPOINT = /foundry-catalog/api/catalog/datasets/ri.foundry.main.dataset.6a23f5c1-f82a-4cb3-b29e-2c7df3ca8398/views/master/files3?pageSize=1000&startTransactionRid=027278bc-aa3f-4d38-a38d-2d1a542fd81d-0-da31aa04-ee69-4abb-943d-57230d2221f7.parquet
-----------------------------------PARAMETERS-----------------------------------
dataset_rid = ri.foundry.main.dataset.6a23f5c1-f82a-4cb3-b29e-2c7df3ca8398
logical_path = None
------------------------------------RESPONSE------------------------------------
STATUS = 400

### Operating System

Windows

### Your python version

Python 3.13.0

**Comment by nicornk** [comment]
https://github.com/emdgroup/foundry-dev-tools/blob/42cccdc4a23b8b70592978affae3af79bcc93356/libs/foundry-dev-tools/src/foundry_dev_tools/clients/catalog.py#L23

We are iterating through all pages to get the number of files.

can you please provide a reproducible example? Your code is not executable.

startTransactionRid=027278bc-aa3f-4d38-a38d-2d1a542fd81d-0-da31aa04-ee69-4abb-943d-57230d2221f7.parquet

this looks odd, a transaction ruf has a different format.

**Comment by lfleck** [comment]
Hi @nicornk, 
I had a similar issue, please find some reproducible code below:

```python 
from pathlib import Path

import polars as pl
from foundry_dev_tools import FoundryContext

ctx = FoundryContext()

# Empty target dataset
output_ds = ctx.get_dataset_by_path(
    "SOME_PATH",
    create_if_not_exist=True
)

# Create dummy parquet file
dummy_df = pl.DataFrame({"test_col": "dummy_value"}).write_parquet(
    "./dummy_file.parquet"
)

# Upload 5000 dummy files
dummy_mapping = {
    f"dummy_file_{i}.parquet": Path("./dummy_file.parquet") for i in range(5000)
}
output_ds.upload_files(
    dummy_mapping,
    max_workers=4,
)

# List files afterwards
output_ds.list_files(page_size=5000) # works
output_ds.list_files(page_size=4999) # raises DatasetNotFoundError
```

I just had a brief look into it (so please take it with a grain of salt), and it seems that the next page token get's passed as start_transaction_rid, while the first batch_result contains a logical_file_path and should hence be passed to the page_start_logical_path instead.

 https://github.com/emdgroup/foundry-dev-tools/blob/42cccdc4a23b8b70592978affae3af79bcc93356/libs/foundry-dev-tools/src/foundry_dev_tools/clients/catalog.py#L81
